name: Repo env example

on: workflow_dispatch

jobs:
  test-env:

   environment: production

   runs-on: ubuntu-latest

   steps:
      - name: Use environment variables
        env:
          API_URL: ${{ vars.API_URL }}
          DB_PASS: ${{secrets.DB_PASSWORD}}
        run: |
          echo "DB_PASSWORD: ${DB_PASS}"
          echo "DB_PASSWORD length :${#DB_PASS}"